# build:
#   stage: build
#   image: docker:19.03.12
#   services:
#     - docker:19.03.12-dind

#   variables:
#     CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
#     CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

#   script:
#     - docker build -t $CONTAINER_TEST_IMAGE .
#     - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - docker push $CONTAINER_RELEASE_IMAGE




deploy:
  stage: deploy
  image: alpine:latest

  before_script:
    - apk update && apk add openssh-client bash rsync
    

  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo "${SSH_HOST_KEY1}" > ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    
    - rsync -vv -rz --checksum --delete . root@196.188.237.74:/var/www/html/landingpage/

  only:
  - master
