import bt from "./assets/image/BT.png";
import BRhotel from "./assets/image/BRUHWAY-HOTEL.png";
import bbm from "./assets/image/bbm-.png";
import star from "./assets/image/STARTIMES.png";
import iphone13 from "./assets/image/cute-girl-pic (12).jpg";
import iphone12 from "./assets/image/iphone2.webp";
import iphone14 from "./assets/image/10-20AK6_phoneFront.png";
export const Relation = [
  {
    key: 1,
    image: BRhotel,
    title: "Company Name ",
    time: "17",
  },
  {
    key: 2,
    image: bt,
    title: "Africa Hote",
    time: "34",
  },
  {
    key: 3,
    image: bbm,
    title: "Skyligh Hotel",
    time: "34",
  },
  {
    key: 4,

    image: star,
    title: "Company Name ",
    time: "34",
  },
  {
    key: 1,
    image: BRhotel,
    title: "Company Name ",
    time: "29",
  },
  {
    key: 2,
    image: bt,
    title: "Company Name ",
    time: "34",
  },
  {
    key: 3,
    image: bbm,
    title: " Company Name ",
    time: "34",
  },
  {
    key: 4,

    image: star,
    title: "Company Name ",
    time: "31",
  },
  {
    key: 2,
    image: bt,
    title: "Company Name ",
    time: "34",
  },
  {
    key: 3,
    image: bbm,
    title: " Company Name ",
    time: "34",
  },
  {
    key: 4,

    image: star,
    title: "Company Name ",
    time: "04",
  },
  {
    key: 4,

    image: star,
    title: "Company Name ",
    time: "24",
  },
];

export const comments = [
  {
    key: 1,
    image: bt,
    Photo: iphone12,
    timestamp: new Date().getTime(),
    CompanyName: "AddisPay",
    message: "Another message from anoter  ",
    fromOther: true,
    description: "Lorem ipsum dolor sit amet ",
    fromMe: false,
  },

  {
    key: 2,
    image: star,
    timestamp: new Date().getTime(),
    CompanyName: "AAu",
    message: "In publishing and graphic design",
    fromOther: true,
    fromMe: true,
  },
  {
    key: 3,
    image: bt,
    CompanyName: "CBE",
    timestamp: new Date().getTime(),
    message: " a typeface without relying on meaningful content. ",
    fromMe: false,
    fromOther: true,
  },
];

export const product = [
  {
    key: 1,
    image: iphone12,
    productName: "Iphone 14 Pro Max",
    place: " in Stock  ",
    price: " 1000$ ",
  },
  {
    key: 1,
    image: iphone12,
    productName: "Iphone 14 Pro Max",
    place: " in Stock  ",
    price: " 1000$ ",
  },
  {
    key: 1,
    image: iphone12,
    productName: "Iphone 14 Pro Max",
    place: " in Stock  ",
    price: " 1000$ ",
  },
  {
    key: 1,
    image: iphone12,
    productName: "Iphone 14 Pro Max",
    place: " in Stock  ",
    price: " 1000$ ",
  },
  {
    key: 1,
    image: iphone12,
    productName: "Iphone 14 Pro Max",
    place: " in Stock  ",
    price: " 1000$ ",
  },
  {
    key: 1,
    image: iphone12,
    productName: "Iphone 14 Pro Max",
    place: " in Stock  ",
    price: " 1000$ ",
  },
  {
    key: 1,
    image: iphone12,
    productName: "Iphone 14 Pro Max",
    place: " in Stock  ",
    price: " 1000$ ",
  },
];
export const Search = [
  {
    key: 1,
    image1: BRhotel,
    Price: "10,000 ",
    productName: " Iphone-13",
    futures: "128 GB Storage",
    ProductFeature: "128 GB Storage",
    ProductFeature: "128 GB Storage",
    image2: iphone12,
    title: "Company Name ",
    description:
      " In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    Product: " iphpne-13",
    isAccepted: false,
    isConnected: true,
  },
  {
    key: 2,
    image1: star,
    Price: "10,000",
    futures: "128 GB Storage",
    productName: "Iphone 14 Pro Max",
    image2: iphone13,
    title: "EagleLion Tech",
    description:
      " In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    isAccepted: false,
    isAccepted: true,
    isConnected: true,
  },
  {
    key: 3,
    image1: bbm,
    Price: "10,000",
    futures: "128 GB Storage",
    productName: "Iphone 14 Pro Max",
    image2: iphone14,
    title: "SkyLight Hotel ",
    description: " relying on meaningful content.",
    isAccepted: false,
    isAccepted: true,
    isConnected: false,
  },
];

export const ChatWithAddisPay = [
  {
    key: 1,
    image: BRhotel,
    Photo: iphone12,
    timestamp: new Date().getTime(),
    CompanyName: "AddisPay",
    message: "Another message from anoter  ",
    fromOther: true,
    description: "Lorem ipsum dolor sit amet ",
    fromMe: false,
  },
  {
    key: 1,
    image: BRhotel,
    Photo: iphone12,
    timestamp: new Date().getTime(),
    CompanyName: "AddisPay",
    message: "Another message from anoter  ",
    fromOther: true,
    description: "jkfhsd fhf fha hf  ",
    fromMe: false,
  },
];

export const EagleChat = [
  {
    key: 1,
    image: star,
    Photo: iphone12,
    timestamp: new Date().getTime(),
    CompanyName: "EagleLion",
    message: "  message from anoter  ",
    fromOther: true,
    description: "I like your company",
    fromMe: false,
  },
  {
    key: 1,
    image: star,
    Photo: iphone12,
    timestamp: new Date().getTime(),
    CompanyName: "EagleLion",
    message: " Addis pay is especial  message from anoter  ",
    fromOther: true,
    description: "I like your company",
    fromMe: false,
  },
  {
    key: 1,
    image: star,
    Photo: iphone12,
    timestamp: new Date().getTime(),
    CompanyName: "EagleLion",
    message: "   i am from 22 Another message from anoter  ",
    fromOther: true,
    description: "I like your company",
    fromMe: false,
  },
  {
    key: 1,
    image: star,
    Photo: iphone12,
    timestamp: new Date().getTime(),
    CompanyName: "EagleLion",
    message: "Another message from anoter  ",
    fromOther: true,
    description: "Please replay soon",
    fromMe: false,
  },
];

export const Chat = [
  {
    key: 1,
    image: BRhotel,
    time: "Joined Jan-2023",
    AmoutOfmessage: "30",
    title: "AddisPay",
    description: "Lorem ipsum dolor sit amet....",
    chatData: ChatWithAddisPay,
    status: "connect",
    productName:""
  },

  {
    key: 2,
    image: star,
    time: "Joined Sep-2023",
    status: "Message",
    title: "EagleLion Tech",
    description: "Lorem ipsum dolor sit amet....",
    chatData: EagleChat,
  },
  {
    key: 2,
    image: star,
    time: "Joined Sep-2023",
    status: "connected",
    title: "EagleLion Tech",
    description: "Lorem ipsum dolor sit amet....",
    chatData: EagleChat,
  },
  {
    key: 3,
    image: bbm,
    time: "Joined Auge-2023",
    AmoutOfmessage: "12",
    title: "SkyLight Hotel ",
    description: "Lorem ipsum dolor sit amet....",
    status: "connect",
    chatData: "",
  },
  {
    key: 4,
    image: bt,
    time: "Joined Feb-2023",
    title: "Company Name ",
    description: "Lorem ipsum dolor sit amet....",
    status: "connected",
    chatData: "",
  },
];
export const Message = [
  {
    key: 1,
    image: BRhotel,
    time: "7:30 am",
    ActiveTime: " since Mar 02,2016 EC",
    AmoutOfMessage: "you have 3 new message",
    title: "Company Name ",
    description:
      "Lorem ipsum dolor sit amet....Lorem ipsum dolor sit amet....Lorem ipsum dolor sit amet....Lorem ipsum dolor sit amet....Lorem ipsum dolor sit amet....Lorem ipsum dolor sit amet....",
  },
  {
    key: 2,

    image: star,
    time: "2:30 pm",
    ActiveTime: " last seen recently",
    title: "EagleLion Tech",
    description: "Lorem ipsum dolor sit amet....",
  },
  {
    key: 2,

    image: star,
    time: "2:30 pm",
    ActiveTime: " last seen recently",
    title: "EagleLion Tech",
    description: "Lorem ipsum dolor sit amet....",
  },
  {
    key: 2,

    image: star,
    time: "2:30 pm",
    ActiveTime: " last seen recently",
    title: "EagleLion Tech",
    description: "Lorem ipsum dolor sit amet....",
  },
  {
    key: 2,

    image: star,
    time: "2:30 pm",
    ActiveTime: " last seen recently",
    title: "EagleLion Tech",
    description: "Lorem ipsum dolor sit amet....",
  },
];

export const Requested = [
  {
    key: 1,
    image: bt,
    title: "Africa Hote",
    time: "34",
  },
  {
    key: 2,
    image: bbm,
    title: "Skyligh Hotel",
    time: "34",
  },
  {
    key: 3,

    image: star,
    title: "Company Name ",
    time: "34",
  },

  {
    key: 4,
    image: bt,
    title: "Company Name ",
    time: "34",
  },
  {
    key: 5,
    image: bbm,
    title: " Company Name ",
    time: "34",
  },
];
export const Recomend = [
  {
    key: 1,
    image: bt,
    title: "Africa Hote",
    time: "34",
  },
  {
    key: 2,
    image: bbm,
    title: "Skyligh Hotel",
    time: "34",
  },
  {
    key: 3,

    image: star,
    title: "Company Name ",
    time: "34",
  },

  {
    key: 4,
    image: bt,
    title: "Company Name ",
    time: "34",
  },
  {
    key: 5,
    image: bbm,
    title: " Company Name ",
    time: "34",
  },
  {
    key: 1,
    image: bt,
    title: "Africa Hote",
    time: "34",
  },
  {
    key: 2,
    image: bbm,
    title: "Skyligh Hotel",
    time: "34",
  },
  {
    key: 3,

    image: star,
    title: "Company Name ",
    time: "34",
  },
];

export const africanCountryCodeMap = {
  DZ: { name: "Algeria", code: "+213" },
  AO: { name: "Angola", code: "+244" },
  BJ: { name: "Benin", code: "+229" },
  BW: { name: "Botswana", code: "+267" },
  BF: { name: "Burkina Faso", code: "+226" },
  BI: { name: "Burundi", code: "+257" },
  CV: { name: "Cabo Verde", code: "+238" },
  CM: { name: "Cameroon", code: "+237" },
  CF: { name: "Central African Republic", code: "+236" },
  TD: { name: "Chad", code: "+235" },
  KM: { name: "Comoros", code: "+269" },
  CG: { name: "Congo (Brazzaville)", code: "+242" },
  CD: { name: "Congo (Kinshasa)", code: "+243" },
  CI: { name: "Côte d'Ivoire", code: "+225" },
  DJ: { name: "Djibouti", code: "+253" },
  EG: { name: "Egypt", code: "+20" },
  GQ: { name: "Equatorial Guinea", code: "+240" },
  ER: { name: "Eritrea", code: "+291" },
  SZ: { name: "Eswatini (formerly Swaziland)", code: "+268" },
  ET: { name: "Ethiopia", code: "+251" },
  GA: { name: "Gabon", code: "+241" },
  GM: { name: "Gambia", code: "+220" },
  GH: { name: "Ghana", code: "+233" },
  GN: { name: "Guinea", code: "+224" },
  GW: { name: "Guinea-Bissau", code: "+245" },
  KE: { name: "Kenya", code: "+254" },
  LS: { name: "Lesotho", code: "+266" },
  LR: { name: "Liberia", code: "+231" },
  LY: { name: "Libya", code: "+218" },
  MG: { name: "Madagascar", code: "+261" },
  MW: { name: "Malawi", code: "+265" },
  ML: { name: "Mali", code: "+223" },
  MR: { name: "Mauritania", code: "+222" },
  MU: { name: "Mauritius", code: "+230" },
  MA: { name: "Morocco", code: "+212" },
  MZ: { name: "Mozambique", code: "+258" },
  NA: { name: "Namibia", code: "+264" },
  NE: { name: "Niger", code: "+227" },
  NG: { name: "Nigeria", code: "+234" },
  RW: { name: "Rwanda", code: "+250" },
  ST: { name: "Sao Tome and Principe", code: "+239" },
  SN: { name: "Senegal", code: "+221" },
  SC: { name: "Seychelles", code: "+248" },
  SL: { name: "Sierra Leone", code: "+232" },
  SO: { name: "Somalia", code: "+252" },
  ZA: { name: "South Africa", code: "+27" },
  SS: { name: "South Sudan", code: "+211" },
  SD: { name: "Sudan", code: "+249" },
  TZ: { name: "Tanzania", code: "+255" },
  TG: { name: "Togo", code: "+228" },
  TN: { name: "Tunisia", code: "+216" },
  UG: { name: "Uganda", code: "+256" },
  ZM: { name: "Zambia", code: "+260" },
  ZW: { name: "Zimbabwe", code: "+263" },
};
export const africanCountryCapitalCity = {
  DZ: { name: "Algeria", code: "+213", capital: "Algiers" },
  AO: { name: "Angola", code: "+244", capital: "Luanda" },
  BJ: { name: "Benin", code: "+229", capital: "Porto-Novo" },
  BW: { name: "Botswana", code: "+267", capital: "Gaborone" },
  BF: { name: "Burkina Faso", code: "+226", capital: "Ouagadougou" },
  BI: { name: "Burundi", code: "+257", capital: "Bujumbura" },
  CV: { name: "Cabo Verde", code: "+238", capital: "Praia" },
  CM: { name: "Cameroon", code: "+237", capital: "Yaoundé" },
  CF: { name: "Central African Republic", code: "+236", capital: "Bangui" },
  TD: { name: "Chad", code: "+235", capital: "N'Djamena" },
  KM: { name: "Comoros", code: "+269", capital: "Moroni" },
  CG: { name: "Congo (Brazzaville)", code: "+242", capital: "Brazzaville" },
  CD: { name: "Congo (Kinshasa)", code: "+243", capital: "Kinshasa" },
  CI: { name: "Côte d'Ivoire", code: "+225", capital: "Yamoussoukro" },
  DJ: { name: "Djibouti", code: "+253", capital: "Djibouti" },
  EG: { name: "Egypt", code: "+20", capital: "Cairo" },
  GQ: { name: "Equatorial Guinea", code: "+240", capital: "Malabo" },
  ER: { name: "Eritrea", code: "+291", capital: "Asmara" },
  SZ: {
    name: "Eswatini (formerly Swaziland)",
    code: "+268",
    capital: "Mbabane",
  },
  ET: { name: "Ethiopia", code: "+251", capital: "Addis Ababa" },
  GA: { name: "Gabon", code: "+241", capital: "Libreville" },
  GM: { name: "Gambia", code: "+220", capital: "Banjul" },
  GH: { name: "Ghana", code: "+233", capital: "Accra" },
  GN: { name: "Guinea", code: "+224", capital: "Conakry" },
  GW: { name: "Guinea-Bissau", code: "+245", capital: "Bissau" },
  KE: { name: "Kenya", code: "+254", capital: "Nairobi" },
  LS: { name: "Lesotho", code: "+266", capital: "Maseru" },
  LR: { name: "Liberia", code: "+231", capital: "Monrovia" },
  LY: { name: "Libya", code: "+218", capital: "Tripoli" },
  MG: { name: "Madagascar", code: "+261", capital: "Antananarivo" },
  MW: { name: "Malawi", code: "+265", capital: "Lilongwe" },
  ML: { name: "Mali", code: "+223", capital: "Bamako" },
  MR: { name: "Mauritania", code: "+222", capital: "Nouakchott" },
  MU: { name: "Mauritius", code: "+230", capital: "Port Louis" },
  MA: { name: "Morocco", code: "+212", capital: "Rabat" },
  MZ: { name: "Mozambique", code: "+258", capital: "Maputo" },
  NA: { name: "Namibia", code: "+264", capital: "Windhoek" },
  NE: { name: "Niger", code: "+227", capital: "Niamey" },
  NG: { name: "Nigeria", code: "+234", capital: "Abuja" },
  RW: { name: "Rwanda", code: "+250", capital: "Kigali" },
  ST: { name: "Sao Tome and Principe", code: "+239", capital: "São Tomé" },
  SN: { name: "Senegal", code: "+221", capital: "Dakar" },
  SC: { name: "Seychelles", code: "+248", capital: "Victoria" },
  SL: { name: "Sierra Leone", code: "+232", capital: "Freetown" },
  SO: { name: "Somalia", code: "+252", capital: "Mogadishu" },
  ZA: { name: "South Africa", code: "+27", capital: "Pretoria" },
  SS: { name: "South Sudan", code: "+211", capital: "Juba" },
  SD: { name: "Sudan", code: "+249", capital: "Khartoum" },
  TZ: { name: "Tanzania", code: "+255", capital: "Dodoma" },
  TG: { name: "Togo", code: "+228", capital: "Lomé" },
  TN: { name: "Tunisia", code: "+216", capital: "Tunis" },
  UG: { name: "Uganda", code: "+256", capital: "Kampala" },
  ZM: { name: "Zambia", code: "+260", capital: "Lusaka" },
  ZW: { name: "Zimbabwe", code: "+263", capital: "Harare" },
};

